# Generated by Django 3.2.8 on 2021-10-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('А', 'А'), ('В', 'В'), ('С', 'С')], default='А', max_length=1, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='registration.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорты',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата создания')),
                ('row_number', models.CharField(blank=True, max_length=50, verbose_name='Первоначальный номер')),
                ('status', models.CharField(choices=[('SUCCESS', 'Успешно'), ('ERROR', 'Ошибка')], default='ERROR', max_length=7, verbose_name='Статус')),
                ('message', models.CharField(max_length=250, verbose_name='Сообщение')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registration.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Регистрация',
                'verbose_name_plural': 'Регистрации',
                'ordering': ('-created',),
            },
        ),
    ]
